baseURL = 'https://gameraccoon.com/'
theme = 'hugo-bearblog'

title = "GameRaccoon"
author = "Pavel Grebnev"
copyright = "Copyright © 2025, Pavel Grebnev."
languageCode = "en-US"

sectionPagesMenu = 'main'
enableRobotsTXT = true

[params]
  description = "Pavel Grebnev CV and blog"

  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  #images = ["images/share.png"]

  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "GameRaccoon"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  # hideMadeWithLine = true

  # By default, if you want to read more than one blog post you have to always go
  # back to the /blog page.
  # By enabling this feature each blog post will have at the end a navigator
  enablePostNavigator = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  # dateFormat = "2006-01-02"

# Configure markup highlighter to match "Bearblog" aesthetics, see
# https://gohugo.io/configuration/markup/#highlight
[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
